# Generated by Django 3.2.6 on 2022-01-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.FloatField()),
                ('entries', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19, unique=True)),
                ('owner', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_num', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('Entrada', 'ENTRADA'), ('Saída', 'SAIDA')], max_length=10)),
                ('signal', models.CharField(choices=[('+', 'ENTRADA'), ('-', 'SAIDA')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('file_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file', to='app.fileorigin')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store', to='app.store')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='app.transactiontype')),
            ],
        ),
    ]
