
version: "3.8"

services:

  db_pg:
    image: postgres:13.4-alpine
    hostname: 'db_pg'
    env_file:
      - ./db.env
    ports:
      - 5433:5432
    volumes:      
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_logbook_net
    restart: always

  app:
    build: 
      context: .
    container_name: my_logbook
    env_file:
      - ./db.env
    volumes:
      - .:/opt/my_logbook
    command: >
      sh -c "python manage.py makemigrations
             python manage.py migrate
             ./manage.py create_superuser_test --username superuser_test --password 1234 --noinput --email 'superuser@test.com'
             python manage.py loaddata app/fixtures/*.json
             python manage.py test
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db_pg
    links:
      - db_pg:db_pg
    depends_on:
      - db_pg
    networks:
      - my_logbook_net

volumes:  
  postgres_data:

networks:
  my_logbook_net:
    driver: bridge
